// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmdvczzryoxngjlmexcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZHZjenpyeW94bmdqbG1leGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MjM2NzAsImV4cCI6MjA2MTI5OTY3MH0.Y3npjQPT_-OWt6RJ481SapoGqbalZQHsxFjPnq3tUo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);